apiVersion: v1
kind: Secret
metadata:
  name: street-scraper-secrets
  namespace: street-scraper
type: Opaque
data:
  SHEET_DOCUMENT_ID: "${SHEET_DOCUMENT_ID}"
  SHEET_CLIENT_EMAIL: "${SHEET_CLIENT_EMAIL}"
  SHEET_CLIENT_PRIVATE_KEY: "${SHEET_CLIENT_PRIVATE_KEY}"
  DISCORD_CHANNEL_ID: "${DISCORD_CHANNEL_ID}"
  DISCORD_TOKEN: "${DISCORD_TOKEN}"
  NOTIVERSAL_API_KEY: "${NOTIVERSAL_API_KEY}"