apiVersion: batch/v1
kind: CronJob
metadata:
  name: street-scraper-cron
  namespace: street-scraper
spec:
  schedule: "*/30 * * * *"
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      # Remove finished jobs after an hour
      ttlSecondsAfterFinished: 3600
      # Terminate jobs taking more than 15 minutes
      activeDeadlineSeconds: 900
      template:
        spec:
          containers:
          - name: screet-scraper
            image: ghcr.io/uen/street-scraper:latest
            imagePullPolicy: Always
            envFrom:
            - secretRef:
                name: street-scraper-secrets
          restartPolicy: OnFailure