apiVersion: batch/v1
kind: CronJob
metadata:
  name: street-scraper-cron
  namespace: street-scraper
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: screet-scraper
            image: ghcr.io/uen/street-scraper:latest
            imagePullPolicy: Always
          restartPolicy: OnFailure